"""Check actual NetworkWorker retry/state transitions with controlled adapters."""
import argparse,pathlib,subprocess,tempfile
p=argparse.ArgumentParser();p.add_argument('--jdk',required=True);a=p.parse_args();jdk=pathlib.Path(a.jdk)/'bin'
root=pathlib.Path(__file__).resolve().parents[1]
sources={
'org/enigmagrid/android/CoordinatorClient.java':'''package org.enigmagrid.android;import java.util.*;import java.io.*;import static org.enigmagrid.core.Canonical.object;
class CoordinatorClient{static class HttpFailure extends IOException{int status;HttpFailure(int s){status=s;}}List<String> calls=Collections.synchronizedList(new ArrayList<>());java.util.concurrent.CountDownLatch uploadEntered,uploadExited;boolean slowComplete;java.util.concurrent.CountDownLatch overlap;java.util.concurrent.CountDownLatch overlapStarted=new java.util.concurrent.CountDownLatch(1);boolean failSettings,failComplete,disabled,required;boolean idle;boolean batches;boolean duplicateBatch;int failAtComplete;String origin(){return "https://test";}CoordinatorClient fork(){return this;}void cancel(){}Map<String,Object> request(String path,Map<String,Object> b,String t)throws Exception{org.enigmagrid.core.Canonical.json(b);calls.add(path);if(path.endsWith("complete")&&uploadEntered!=null){uploadEntered.countDown();try{Thread.sleep(10000);}finally{uploadExited.countDown();}}if(path.endsWith("complete")&&overlap!=null)overlapStarted.countDown();if(path.endsWith("complete")&&overlap!=null&&!overlap.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("No compute/upload overlap");if(path.endsWith("complete")&&slowComplete){slowComplete=false;Thread.sleep(21500);}if(path.endsWith("settings")&&failSettings)throw new IOException();if(path.endsWith("complete")&&(failComplete||count("complete")==failAtComplete))throw new IOException();if(path.endsWith("leases")){if(!batches)throw new HttpFailure(404);return object("enabled",true,"leases",Arrays.asList(object("id","a","work_token","s"),object("id",duplicateBatch?"a":"b","work_token","s")));}if(path.endsWith("lease"))return object("enabled",!disabled,"update_required",required,"lease",idle?null:object("id","lease","work_token","secret"));return object("ok",true);}int count(String suffix){synchronized(calls){return (int)calls.stream().filter(s->s.endsWith(suffix)).count();}}}
''',
'org/enigmagrid/android/CredentialStore.java':'''package org.enigmagrid.android;import java.util.*;class CredentialStore{Map<String,Object> value;CredentialStore pending;Map<String,Object> load(){return value;}void save(Map<String,Object> v){value=v;}void clear(){value=null;}CredentialStore pendingResults(){if(pending==null)pending=new CredentialStore();return pending;}}''',
'org/enigmagrid/android/Enrollment.java':'''package org.enigmagrid.android;import java.util.*;class Enrollment{static Map<String,Object> metadata(){return new HashMap<>();}}''',
'org/enigmagrid/core/WorkEnvelope.java':'''package org.enigmagrid.core;import java.util.*;import java.util.function.*;import static org.enigmagrid.core.Canonical.object;public class WorkEnvelope{public static java.util.function.Consumer<Map<String,Object>> onRun=l->{};public static void validate(Map<String,Object> m){}public static Map<String,Object> run(Map<String,Object> l,BooleanSupplier c,BoundedCrib.RowProvider r,int n){onRun.accept(l);return object("receipt",object("candidates",new ArrayList<>()));}}''',
'org/enigmagrid/android/NetworkCycleChecks.java':'''package org.enigmagrid.android;import java.util.*;import java.io.*;import static org.enigmagrid.core.Canonical.object;
public class NetworkCycleChecks{static void check(boolean b){if(!b)throw new AssertionError();}public static void main(String[] args)throws Exception{
CoordinatorClient c=new CoordinatorClient();CredentialStore s=new CredentialStore();s.save(object("server",c.origin(),"device_token","token"));NetworkWorker w=new NetworkWorker(c,s);Map<String,Object> settings=object("cpu_percent",100);
w.once(()->false,settings);w.once(()->false,settings);check(c.count("settings")==1&&c.count("heartbeat")==0&&c.count("complete")==2);
c.idle=true;w.once(()->false,settings);check(!w.acknowledgedWork());c.idle=false;
settings.put("cpu_percent",50);c.failSettings=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IOException expected){}c.failSettings=false;w.once(()->false,settings);check(c.count("settings")==3);
c.failComplete=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IOException expected){}check(s.pendingResults().load()!=null&&!w.acknowledgedWork());int leases=c.count("lease");c.failComplete=false;w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).isEmpty()&&w.acknowledgedWork()&&c.count("lease")==leases);
s.pendingResults().save(object("server",c.origin(),"owner",org.enigmagrid.core.Canonical.digest("token"),"submission",object("lease_id","legacy","work_token","secret")));w.once(()->false,settings);check(w.acknowledgedWork()&&c.count("lease")==leases);
s.pendingResults().save(object("server",c.origin(),"owner",org.enigmagrid.core.Canonical.digest("token"),"submissions",new ArrayList<>(Arrays.asList(object("lease_id","a"),object("lease_id","b")))));w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).size()==1);w=new NetworkWorker(c,s);w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).isEmpty()&&c.count("lease")==leases);
int completed=c.count("complete");c.disabled=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IllegalStateException expected){}check(!w.acknowledgedWork()&&c.count("complete")==completed);c.disabled=false;c.required=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IllegalStateException expected){}check(c.count("complete")==completed);
CoordinatorClient batch=new CoordinatorClient();batch.batches=true;CredentialStore bs=new CredentialStore();bs.save(object("server",batch.origin(),"device_token","batch-token"));new NetworkWorker(batch,bs,null).once(()->false);check(batch.count("leases")==1&&batch.count("complete")==2);
CoordinatorClient old=new CoordinatorClient();CredentialStore os=new CredentialStore();os.save(object("server",old.origin(),"device_token","old-token"));NetworkWorker ow=new NetworkWorker(old,os,null);ow.once(()->false);ow.once(()->false);check(old.count("leases")==1&&old.count("lease")==2&&old.count("complete")==2);
CoordinatorClient broken=new CoordinatorClient();broken.batches=true;broken.failAtComplete=2;CredentialStore durable=new CredentialStore();durable.save(object("server",broken.origin(),"device_token","batch-token"));NetworkWorker bw=new NetworkWorker(broken,durable,null,true);try{bw.once(()->false);throw new AssertionError();}catch(IOException expected){}List<?> left=(List<?>)durable.pendingResults().load().get("submissions");check(left.size()==1&&"b".equals(((Map<?,?>)left.get(0)).get("lease_id")));int requests=broken.count("leases");new NetworkWorker(broken,durable,null,true).once(()->false);check(broken.count("leases")==requests&&((List<?>)durable.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient duplicate=new CoordinatorClient();duplicate.batches=true;duplicate.duplicateBatch=true;CredentialStore ds=new CredentialStore();ds.save(object("server",duplicate.origin(),"device_token","token"));try{new NetworkWorker(duplicate,ds,null,true).once(()->false);throw new AssertionError();}catch(IllegalArgumentException expected){}check(duplicate.count("complete")==0&&ds.pendingResults().load()==null);
CoordinatorClient firstFailure=new CoordinatorClient();firstFailure.batches=true;firstFailure.failAtComplete=1;CredentialStore fs=new CredentialStore();fs.save(object("server",firstFailure.origin(),"device_token","token"));try{new NetworkWorker(firstFailure,fs).once(()->false);throw new AssertionError();}catch(IOException expected){}check(((List<?>)fs.pendingResults().load().get("submissions")).size()==2);NetworkWorker recover=new NetworkWorker(firstFailure,fs);recover.once(()->false);recover.once(()->false);check(firstFailure.count("leases")==1&&((List<?>)fs.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient overlap=new CoordinatorClient();overlap.batches=true;overlap.overlap=new java.util.concurrent.CountDownLatch(1);NetworkWorker[] observed=new NetworkWorker[1];org.enigmagrid.core.WorkEnvelope.onRun=l->{if("b".equals(l.get("id"))){try{check(overlap.overlapStarted.await(2,java.util.concurrent.TimeUnit.SECONDS));}catch(InterruptedException e){throw new RuntimeException(e);}check(observed[0].phase().contains("uploading previous result"));overlap.overlap.countDown();}};CredentialStore overlapStore=new CredentialStore();overlapStore.save(object("server",overlap.origin(),"device_token","token"));observed[0]=new NetworkWorker(overlap,overlapStore);observed[0].once(()->false);check(!observed[0].phase().contains("uploading previous result"));check(overlap.count("complete")==2&&((List<?>)overlapStore.pendingResults().load().get("submissions")).isEmpty());org.enigmagrid.core.WorkEnvelope.onRun=l->{};
CoordinatorClient stopped=new CoordinatorClient();stopped.batches=true;stopped.uploadEntered=new java.util.concurrent.CountDownLatch(1);stopped.uploadExited=new java.util.concurrent.CountDownLatch(1);CredentialStore stopStore=new CredentialStore();stopStore.save(object("server",stopped.origin(),"device_token","token"));long stopStart=System.nanoTime();try{new NetworkWorker(stopped,stopStore).once(()->stopped.uploadEntered.getCount()==0);throw new AssertionError("Stop ignored");}catch(java.util.concurrent.CancellationException expected){}check(stopped.uploadExited.await(1,java.util.concurrent.TimeUnit.SECONDS));check((System.nanoTime()-stopStart)/1_000_000<3000);check(!((List<?>)stopStore.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient slow=new CoordinatorClient();slow.batches=true;slow.slowComplete=true;CredentialStore ss=new CredentialStore();ss.save(object("server",slow.origin(),"device_token","slow-token"));new NetworkWorker(slow,ss).once(()->false);check(slow.count("heartbeat")>=1&&slow.count("complete")==2);
System.out.println("PASS: repeated work, idle reset, settings retry, durable replay, disable, mandatory update, batch partial failure and restart, compute/upload overlap, blocked-upload cancellation and retained receipts, duplicate batch rejection, legacy fallback");}}
'''
}
with tempfile.TemporaryDirectory(prefix='enigma-network-cycle-') as folder:
 d=pathlib.Path(folder);files=[]
 for name,source in sources.items():
  f=d/name;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(source,encoding='utf-8');files.append(str(f))
 files += [str(f) for f in (root/'core/src/main/java').rglob('*.java') if f.name!='WorkEnvelope.java']
 files.append(str(root/'app/src/main/java/org/enigmagrid/android/NetworkWorker.java'))
 subprocess.run([str(jdk/'javac.exe'),'-encoding','UTF-8','-d',str(d),*files],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.android.NetworkCycleChecks'],check=True)
