"""Check actual NetworkWorker retry/state transitions with controlled adapters."""
import argparse,pathlib,subprocess,tempfile
p=argparse.ArgumentParser();p.add_argument('--jdk',required=True);a=p.parse_args();jdk=pathlib.Path(a.jdk)/'bin'
root=pathlib.Path(__file__).resolve().parents[1]
sources={
'org/enigmagrid/android/CoordinatorClient.java':'''package org.enigmagrid.android;import java.util.*;import java.io.*;import static org.enigmagrid.core.Canonical.object;
class CoordinatorClient{static class HttpFailure extends IOException{int status;HttpFailure(int s){status=s;}}List<String> calls=Collections.synchronizedList(new ArrayList<>());java.util.concurrent.CountDownLatch uploadEntered,uploadExited;boolean slowComplete;boolean prefetch;java.util.concurrent.CountDownLatch prefetchStarted=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.CountDownLatch computeEntered=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.CountDownLatch overlap;java.util.concurrent.CountDownLatch overlapStarted=new java.util.concurrent.CountDownLatch(1);boolean failSettings,failComplete,disabled,required;boolean idle;boolean batches;boolean duplicateBatch;int failAtComplete;String origin(){return "https://test";}CoordinatorClient fork(){return this;}void cancel(){}Map<String,Object> request(String path,Map<String,Object> b,String t)throws Exception{org.enigmagrid.core.Canonical.json(b);calls.add(path);if(path.endsWith("complete")&&uploadEntered!=null){uploadEntered.countDown();try{Thread.sleep(10000);}finally{uploadExited.countDown();}}if(path.endsWith("complete")&&overlap!=null)overlapStarted.countDown();if(path.endsWith("complete")&&overlap!=null&&!overlap.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("No compute/upload overlap");if(path.endsWith("complete")&&slowComplete){slowComplete=false;Thread.sleep(21500);}if(path.endsWith("settings")&&failSettings)throw new IOException();if(path.endsWith("complete")&&(failComplete||count("complete")==failAtComplete))throw new IOException();if(path.endsWith("leases")){if(prefetch&&count("leases")>1){prefetchStarted.countDown();if(!computeEntered.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("No allocation/compute overlap");return object("enabled",true,"leases",count("leases")==2?Arrays.asList(object("id","a","work_token","s"),object("id","b","work_token","s"),object("id","c","work_token","s")):Arrays.asList(object("id","c","work_token","s")));}if(!batches)throw new HttpFailure(404);return object("enabled",true,"leases",Arrays.asList(object("id","a","work_token","s"),object("id",duplicateBatch?"a":"b","work_token","s")));}if(path.endsWith("lease"))return object("enabled",!disabled,"update_required",required,"lease",idle?null:object("id","lease","work_token","secret"));return object("ok",true);}int count(String suffix){synchronized(calls){return (int)calls.stream().filter(s->s.endsWith(suffix)).count();}}}
''',
'org/enigmagrid/android/CredentialStore.java':'''package org.enigmagrid.android;import java.util.*;class CredentialStore{Map<String,Object> value;CredentialStore pending,blocks,expired;Map<String,Map<String,Object>> records=new HashMap<>();org.enigmagrid.core.ReceiptQueue.Storage workBlockStorage(){CredentialStore b=workBlocks();return new org.enigmagrid.core.ChunkedBlockStorage(new org.enigmagrid.core.ReceiptQueue.Storage(){public Map<String,Object> load(){return b.load();}public void save(Map<String,Object> v){b.save(v);}},new org.enigmagrid.core.ChunkedBlockStorage.Records(){public Map<String,Object> load(String h){return b.records.get(h);}public void save(String h,Map<String,Object> v){b.records.put(h,v);}public void retain(Set<String> h){b.records.keySet().retainAll(h);}},128*1024);}CredentialStore expiredResults(){if(expired==null)expired=new CredentialStore();return expired;}CredentialStore workBlocks(){if(blocks==null)blocks=new CredentialStore();return blocks;}Map<String,Object> load(){return value;}void save(Map<String,Object> v){value=v;}void clear(){value=null;}CredentialStore pendingResults(){if(pending==null)pending=new CredentialStore();return pending;}}''',
'org/enigmagrid/android/Enrollment.java':'''package org.enigmagrid.android;import java.util.*;class Enrollment{static Map<String,Object> metadata(){return new HashMap<>();}}''',
'org/enigmagrid/core/WorkEnvelope.java':'''package org.enigmagrid.core;import java.util.*;import java.util.function.*;import static org.enigmagrid.core.Canonical.object;public class WorkEnvelope{public static java.util.function.Consumer<Map<String,Object>> onRun=l->{};public static Map<String,Object> validate(Map<String,Object> m){return m;}public static Map<String,Object> run(Map<String,Object> l,BooleanSupplier c,BoundedCrib.RowProvider r,int n){onRun.accept(l);return object("receipt",object("candidates",new ArrayList<>()));}}''',
'org/enigmagrid/android/NetworkCycleChecks.java':'''package org.enigmagrid.android;import java.util.*;import java.io.*;import static org.enigmagrid.core.Canonical.object;
public class NetworkCycleChecks{static void check(boolean b){if(!b)throw new AssertionError();}public static void main(String[] args)throws Exception{
CoordinatorClient c=new CoordinatorClient();CredentialStore s=new CredentialStore();s.save(object("server",c.origin(),"device_token","token"));NetworkWorker w=new NetworkWorker(c,s);Map<String,Object> settings=object("cpu_percent",100);
w.once(()->false,settings);w.once(()->false,settings);check(c.count("settings")==1&&c.count("heartbeat")==0&&c.count("complete")==2);check(w.completedJobs()==2&&w.completedUnits()==2&&w.wallSeconds()>0&&w.computeSeconds()>=0&&w.leaseWaitSeconds()>0&&w.uploadWaitSeconds()>0);
c.idle=true;w.once(()->false,settings);check(!w.acknowledgedWork()&&w.completedJobs()==2&&w.completedUnits()==2);c.idle=false;
settings.put("cpu_percent",50);c.failSettings=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IOException expected){}c.failSettings=false;w.once(()->false,settings);check(c.count("settings")==3);
c.failComplete=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IOException expected){}check(s.pendingResults().load()!=null&&!w.acknowledgedWork());int leases=c.count("lease");c.failComplete=false;w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).isEmpty()&&w.acknowledgedWork()&&c.count("lease")==leases);
s.pendingResults().save(object("server",c.origin(),"owner",org.enigmagrid.core.Canonical.digest("token"),"submission",object("lease_id","legacy","work_token","secret")));w.once(()->false,settings);check(w.acknowledgedWork()&&c.count("lease")==leases);
s.pendingResults().save(object("server",c.origin(),"owner",org.enigmagrid.core.Canonical.digest("token"),"submissions",new ArrayList<>(Arrays.asList(object("lease_id","a"),object("lease_id","b")))));w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).size()==1);w=new NetworkWorker(c,s);w.once(()->false,settings);check(((List<?>)s.pendingResults().load().get("submissions")).isEmpty()&&c.count("lease")==leases);
int completed=c.count("complete");c.disabled=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IllegalStateException expected){}check(!w.acknowledgedWork()&&c.count("complete")==completed);c.disabled=false;c.required=true;try{w.once(()->false,settings);throw new AssertionError();}catch(IllegalStateException expected){}check(c.count("complete")==completed);
for(boolean deny:new boolean[]{false,true}){
 java.util.concurrent.CountDownLatch present=new java.util.concurrent.CountDownLatch(1),refused=new java.util.concurrent.CountDownLatch(1);
 CoordinatorClient cooling=new CoordinatorClient(){@Override Map<String,Object> request(String path,Map<String,Object> body,String token){check(path.equals("/api/heartbeat"));check(token.equals("cooling-token"));present.countDown();return object("enabled",!deny);}};
 CredentialStore coolingStore=new CredentialStore();coolingStore.save(object("server",cooling.origin(),"device_token","cooling-token"));
 NetworkWorker coolingWorker=new NetworkWorker(cooling,coolingStore);
 try{coolingWorker.startPresence(()->"Cooling battery",refused::countDown);check(present.await(2,java.util.concurrent.TimeUnit.SECONDS));if(deny)check(refused.await(2,java.util.concurrent.TimeUnit.SECONDS));check(coolingWorker.completedJobs()==0&&coolingStore.pendingResults().load()==null);}
 finally{coolingWorker.stopPresence();}
}
CoordinatorClient batch=new CoordinatorClient();batch.batches=true;CredentialStore bs=new CredentialStore();bs.save(object("server",batch.origin(),"device_token","batch-token"));new NetworkWorker(batch,bs,null).once(()->false);check(batch.count("leases")==1&&batch.count("complete")==2);
CoordinatorClient old=new CoordinatorClient();CredentialStore os=new CredentialStore();os.save(object("server",old.origin(),"device_token","old-token"));NetworkWorker ow=new NetworkWorker(old,os,null);ow.once(()->false);ow.once(()->false);check(old.count("leases")==1&&old.count("lease")==2&&old.count("complete")==2);
CoordinatorClient broken=new CoordinatorClient();broken.batches=true;broken.failAtComplete=2;CredentialStore durable=new CredentialStore();durable.save(object("server",broken.origin(),"device_token","batch-token"));NetworkWorker bw=new NetworkWorker(broken,durable,null,true);try{bw.once(()->false);throw new AssertionError();}catch(IOException expected){}List<?> left=(List<?>)durable.pendingResults().load().get("submissions");check(left.size()==1&&"b".equals(((Map<?,?>)left.get(0)).get("lease_id")));int requests=broken.count("leases");new NetworkWorker(broken,durable,null,true).once(()->false);check(broken.count("leases")==requests&&((List<?>)durable.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient duplicate=new CoordinatorClient();duplicate.batches=true;duplicate.duplicateBatch=true;CredentialStore ds=new CredentialStore();ds.save(object("server",duplicate.origin(),"device_token","token"));try{new NetworkWorker(duplicate,ds,null,true).once(()->false);throw new AssertionError();}catch(IllegalArgumentException expected){}check(duplicate.count("complete")==0&&ds.pendingResults().load()==null);
CoordinatorClient firstFailure=new CoordinatorClient();firstFailure.batches=true;firstFailure.failAtComplete=1;CredentialStore fs=new CredentialStore();fs.save(object("server",firstFailure.origin(),"device_token","token"));NetworkWorker failedWorker=new NetworkWorker(firstFailure,fs);try{failedWorker.once(()->false);throw new AssertionError();}catch(IOException expected){}int savedCount=((List<?>)fs.pendingResults().load().get("submissions")).size();check(savedCount>=1&&savedCount==failedWorker.completedJobs());NetworkWorker recover=new NetworkWorker(firstFailure,fs);for(int savedIndex=0;savedIndex<savedCount;savedIndex++)recover.once(()->false);check(firstFailure.count("leases")==1&&((List<?>)fs.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient overlap=new CoordinatorClient();overlap.batches=true;overlap.overlap=new java.util.concurrent.CountDownLatch(1);NetworkWorker[] observed=new NetworkWorker[1];org.enigmagrid.core.WorkEnvelope.onRun=l->{if("b".equals(l.get("id"))){try{check(overlap.overlapStarted.await(2,java.util.concurrent.TimeUnit.SECONDS));}catch(InterruptedException e){throw new RuntimeException(e);}check(observed[0].phase().contains("uploading previous result"));overlap.overlap.countDown();}};CredentialStore overlapStore=new CredentialStore();overlapStore.save(object("server",overlap.origin(),"device_token","token"));observed[0]=new NetworkWorker(overlap,overlapStore);observed[0].once(()->false);check(!observed[0].phase().contains("uploading previous result"));check(overlap.count("complete")==2&&((List<?>)overlapStore.pendingResults().load().get("submissions")).isEmpty());org.enigmagrid.core.WorkEnvelope.onRun=l->{};
CoordinatorClient stopped=new CoordinatorClient();stopped.batches=true;stopped.uploadEntered=new java.util.concurrent.CountDownLatch(1);stopped.uploadExited=new java.util.concurrent.CountDownLatch(1);CredentialStore stopStore=new CredentialStore();stopStore.save(object("server",stopped.origin(),"device_token","token"));long stopStart=System.nanoTime();try{new NetworkWorker(stopped,stopStore).once(()->stopped.uploadEntered.getCount()==0);throw new AssertionError("Stop ignored");}catch(java.util.concurrent.CancellationException expected){}check(stopped.uploadExited.await(1,java.util.concurrent.TimeUnit.SECONDS));check((System.nanoTime()-stopStart)/1_000_000<3000);check(!((List<?>)stopStore.pendingResults().load().get("submissions")).isEmpty());
CoordinatorClient pre=new CoordinatorClient();pre.batches=true;pre.prefetch=true;CredentialStore ps=new CredentialStore();ps.save(object("server",pre.origin(),"device_token","prefetch-token"));NetworkWorker pw=new NetworkWorker(pre,ps);pw.enableContinuousPrefetch();Set<String> computed=new HashSet<>();org.enigmagrid.core.WorkEnvelope.onRun=l->{if(!computed.add((String)l.get("id")))throw new AssertionError("Replayed lease executed twice");pre.computeEntered.countDown();try{check(pre.prefetchStarted.await(2,java.util.concurrent.TimeUnit.SECONDS));}catch(InterruptedException e){throw new RuntimeException(e);}};pw.once(()->false);check(computed.equals(new HashSet<>(Arrays.asList("a","b","c")))&&pw.completedJobs()==3&&pre.count("complete")==3);org.enigmagrid.core.WorkEnvelope.onRun=l->{};
java.util.concurrent.CountDownLatch refilledAfterReplay=new java.util.concurrent.CountDownLatch(1);
CoordinatorClient replayOnly=new CoordinatorClient(){int allocations;@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{if(!path.endsWith("leases"))return super.request(path,body,token);calls.add(path);allocations++;if(allocations==3)refilledAfterReplay.countDown();return object("enabled",true,"leases",allocations<=2?Arrays.asList(object("id","a","work_token","s"),object("id","b","work_token","s")):allocations==3?Arrays.asList(object("id","c","work_token","s")):Collections.emptyList());}};
CredentialStore replayStore=new CredentialStore();replayStore.save(object("server",replayOnly.origin(),"device_token","replay-token"));NetworkWorker replayWorker=new NetworkWorker(replayOnly,replayStore);replayWorker.enableContinuousPrefetch();Set<String> replayComputed=new HashSet<>();org.enigmagrid.core.WorkEnvelope.onRun=l->{check(replayComputed.add((String)l.get("id")));if("a".equals(l.get("id")))try{if(!refilledAfterReplay.await(3,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Replay-only response disabled prefetch while computing");}catch(InterruptedException e){throw new RuntimeException(e);}};replayWorker.once(()->false);check(replayComputed.equals(new HashSet<>(Arrays.asList("a","b","c")))&&replayWorker.completedJobs()==3);org.enigmagrid.core.WorkEnvelope.onRun=l->{};
// Server commits a receipt, but its HTTP acknowledgement is delayed while
// another connection allocates work. The local reservation remains occupied.
for(boolean negotiated:new boolean[]{false,true}){
java.util.concurrent.CountDownLatch allocationDuringAck=new java.util.concurrent.CountDownLatch(1);
CoordinatorClient delayedAck=new CoordinatorClient(){int allocations;boolean blocked;@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
 if(path.endsWith("complete")&&!blocked){blocked=true;try{if(!allocationDuringAck.await(3,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("No prefetch during delayed acknowledgement");}catch(InterruptedException e){throw new RuntimeException(e);}}
 if(!path.endsWith("leases"))return super.request(path,body,token);
 calls.add(path);allocations++;List<Map<String,Object>> assigned=new ArrayList<>();
 if(allocations==1){for(int i=0;i<4;i++)assigned.add(object("id","old"+i,"work_token","s"));}
 else if(allocations==2){int requested=((Number)body.get("count")).intValue();for(int i=1;i<4;i++)assigned.add(object("id","old"+i,"work_token","s"));int fresh=negotiated?Math.min(requested-3,((Number)body.get("max_new")).intValue()):requested-3;for(int i=0;i<fresh;i++)assigned.add(object("id","new"+i,"work_token","s"));}
 return object("enabled",true,"leases",assigned,"new_lease_limit",negotiated);
}};
CredentialStore delayedStore=new CredentialStore();delayedStore.save(object("server",delayedAck.origin(),"device_token","delayed-token"));NetworkWorker delayedWorker=new NetworkWorker(delayedAck,delayedStore);delayedWorker.enableContinuousPrefetch();Set<String> delayedComputed=new HashSet<>();org.enigmagrid.core.WorkEnvelope.onRun=l->{check(delayedComputed.add((String)l.get("id")));if(((String)l.get("id")).startsWith("new"))allocationDuringAck.countDown();};delayedWorker.once(()->false);check(delayedWorker.completedJobs()>4&&delayedWorker.completedJobs()<=32&&((List<?>)delayedStore.pendingResults().load().get("submissions")).isEmpty());org.enigmagrid.core.WorkEnvelope.onRun=l->{};
}
CoordinatorClient gap=new CoordinatorClient(){int allocations;@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
 if(!path.endsWith("leases"))return super.request(path,body,token);
 calls.add(path);allocations++;
 return object("enabled",true,"retry_after_seconds",1,"leases",allocations==1?Arrays.asList(object("id","a","work_token","s")):allocations==3?Arrays.asList(object("id","b","work_token","s")):Collections.emptyList());
}};gap.batches=true;CredentialStore gapStore=new CredentialStore();gapStore.save(object("server",gap.origin(),"device_token","gap-token"));NetworkWorker gapWorker=new NetworkWorker(gap,gapStore);gapWorker.enablePersistentPipeline();long gapStarted=System.nanoTime();
try{gapWorker.once(()->{if(System.nanoTime()-gapStarted>5_000_000_000L)throw new AssertionError("Persistent pipeline did not resume after empty batch");return gapWorker.completedJobs()==2&&gapWorker.pendingResults()==0;});throw new AssertionError("Persistent pipeline exited before stop");}catch(java.util.concurrent.CancellationException expected){}
check(gapWorker.completedJobs()==2&&gap.count("complete")==2&&gap.count("leases")>=3);
CoordinatorClient parallel=new CoordinatorClient();parallel.batches=true;CredentialStore parallelStore=new CredentialStore();parallelStore.save(object("server",parallel.origin(),"device_token","parallel-token"));NetworkWorker concurrent=new NetworkWorker(parallel,parallelStore);concurrent.setParallelJobs(2);java.util.concurrent.CountDownLatch together=new java.util.concurrent.CountDownLatch(2);org.enigmagrid.core.WorkEnvelope.onRun=l->{together.countDown();try{if(!together.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Jobs did not run concurrently");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new RuntimeException(e);}};concurrent.once(()->false);check(concurrent.completedJobs()==2&&parallel.count("complete")==2&&((List<?>)parallelStore.pendingResults().load().get("submissions")).isEmpty());org.enigmagrid.core.WorkEnvelope.onRun=l->{};
CoordinatorClient slow=new CoordinatorClient();slow.batches=true;slow.slowComplete=true;CredentialStore ss=new CredentialStore();ss.save(object("server",slow.origin(),"device_token","slow-token"));new NetworkWorker(slow,ss).once(()->false);check(slow.count("heartbeat")>=1&&slow.count("complete")==2);
Set<String> blockReceived=Collections.synchronizedSet(new HashSet<>());
CoordinatorClient blocks=new CoordinatorClient(){Map<String,String> ids=new HashMap<>();@Override synchronized Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
 if(path.equals("/api/capabilities"))return object("long_work_blocks",org.enigmagrid.core.WorkBlock.FORMAT,"work_result_groups",org.enigmagrid.core.WorkBlockTransport.GROUP_FORMAT);
 if(path.equals("/api/work-blocks")){calls.add(path);String id=ids.computeIfAbsent((String)body.get("request_id"),k->"block"+ids.size());return object("status","reserved","block",object("format",org.enigmagrid.core.WorkBlock.FORMAT,"block_id",id,"engine","bounded_crib_v1","start_unit",0,"end_unit",1000,"config",object("requires",Arrays.asList("cpu","bounded_crib_v1"),"program",object("ciphertext","BDZGO","hypotheses",Arrays.asList(object("text","BD","legal_clean_offsets",Arrays.asList(0))),"chunk",3,"ordinal_base",0,"candidate_limit",3))));}
 if(path.endsWith("/status")){List<Object> states=new ArrayList<>();for(Object id:(List<?>)body.get("blocks"))states.add(object("block_id",id,"status","reserved","valid_for_seconds",600));return object("blocks",states);}
 if(path.endsWith("/result-groups")){org.enigmagrid.core.WorkBlockJson.json(body);List<Object> ack=new ArrayList<>();for(Object group:(List<?>)body.get("groups"))for(Object raw:(List<?>)group){Object unit=((Map<?,?>)raw).get("unit");blockReceived.add(body.get("block_id")+":"+unit);ack.add(object("unit",unit,"status","received"));}return object("block_id",body.get("block_id"),"results",ack);}
 if(path.endsWith("/release"))return object("block_id",body.get("block_id"),"released",true);
 return super.request(path,body,token);
}};
CredentialStore blockStore=new CredentialStore();blockStore.save(object("server",blocks.origin(),"device_token","block-token"));NetworkWorker blockWorker=new NetworkWorker(blocks,blockStore);blockWorker.enablePersistentPipeline();blockWorker.setParallelJobs(4);java.util.concurrent.CountDownLatch blockTogether=new java.util.concurrent.CountDownLatch(4);org.enigmagrid.core.WorkEnvelope.onRun=l->{blockTogether.countDown();try{if(!blockTogether.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Long blocks did not overlap");}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new java.util.concurrent.CancellationException();}};long blockStarted=System.nanoTime();
try{blockWorker.once(()->{if(System.nanoTime()-blockStarted>5_000_000_000L)throw new AssertionError("Negotiated block pipeline stalled");return blockWorker.completedJobs()>=10;});throw new AssertionError("Block stop ignored");}catch(java.util.concurrent.CancellationException expected){}
Set<String> recovered=new HashSet<>(blockReceived);List<?> blockPending=(List<?>)blockStore.workBlockStorage().load().get("pending");for(Object raw:blockPending){Map<?,?> row=(Map<?,?>)raw;recovered.add(row.get("block_id")+":"+row.get("unit"));}
check(blockWorker.completedJobs()>=10&&blockWorker.completedJobs()<=13&&recovered.size()==blockWorker.completedJobs()&&blocks.count("leases")==0&&blocks.count("lease")==0);org.enigmagrid.core.WorkEnvelope.onRun=l->{};
CoordinatorClient calibration=new CoordinatorClient(){int negotiations;@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
 if(path.equals("/api/capabilities")){negotiations++;return object("long_work_blocks",org.enigmagrid.core.WorkBlock.FORMAT);}
 if(path.equals("/api/work-blocks"))return object("block",null,"wait_reason","block_calibration_required");
 return super.request(path,body,token);
}};calibration.batches=true;CredentialStore calibrationStore=new CredentialStore();calibrationStore.save(object("server",calibration.origin(),"device_token","calibration-token"));NetworkWorker calibrationWorker=new NetworkWorker(calibration,calibrationStore);calibrationWorker.enablePersistentPipeline();long calibrationStarted=System.nanoTime();
for(int i=0;i<2;i++)calibrationWorker.once(()->{if(System.nanoTime()-calibrationStarted>5_000_000_000L)throw new AssertionError("Legacy calibration never returned to negotiation");return false;});
check(calibration.count("leases")==2&&calibrationWorker.completedJobs()==4);
for(String flag:Arrays.asList("enabled","update_required")){
 CoordinatorClient denied=new CoordinatorClient(){@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
  if(path.equals("/api/capabilities"))return object("long_work_blocks",org.enigmagrid.core.WorkBlock.FORMAT);
  if(path.equals("/api/work-blocks"))return object(flag,!flag.equals("enabled"),"block",null);
  return super.request(path,body,token);
 }};CredentialStore deniedStore=new CredentialStore();deniedStore.save(object("server",denied.origin(),"device_token","denied-token"));NetworkWorker deniedWorker=new NetworkWorker(denied,deniedStore);deniedWorker.enablePersistentPipeline();long deniedStarted=System.nanoTime();
 try{deniedWorker.once(()->{if(System.nanoTime()-deniedStarted>3_000_000_000L)throw new AssertionError("Block policy refusal ignored");return false;});throw new AssertionError("Policy accepted");}catch(IllegalStateException expected){}
check(deniedWorker.completedJobs()==0&&denied.count("leases")==0);
}
// A coordinator may advertise telemetry while returning only legacy leases.
// Keep one reporter across repeated capability probes and close it with the
// worker, not each short legacy transaction.
CoordinatorClient legacyTelemetry=new CoordinatorClient(){@Override Map<String,Object> request(String path,Map<String,Object> body,String token)throws Exception{
 if(path.equals("/api/capabilities"))return object("device_telemetry","device_telemetry_v1","server_time_ms",System.currentTimeMillis());
 return super.request(path,body,token);
}};legacyTelemetry.batches=true;
CredentialStore legacyTelemetryStore=new CredentialStore();legacyTelemetryStore.save(object("server",legacyTelemetry.origin(),"device_token","legacy-telemetry-token"));
NetworkWorker legacyTelemetryWorker=new NetworkWorker(legacyTelemetry,legacyTelemetryStore);legacyTelemetryWorker.enablePersistentPipeline();
java.util.concurrent.atomic.AtomicInteger reporterCreated=new java.util.concurrent.atomic.AtomicInteger(),reporterStarted=new java.util.concurrent.atomic.AtomicInteger(),reporterClosed=new java.util.concurrent.atomic.AtomicInteger();
legacyTelemetryWorker.setTelemetryFactory((token,worker,serverTimeMs,receivedNs)->{check(token.equals("legacy-telemetry-token")&&serverTimeMs>0&&receivedNs>0);reporterCreated.incrementAndGet();
 return new NetworkWorker.TelemetrySession(){public void start(){reporterStarted.incrementAndGet();}public void close(){reporterClosed.incrementAndGet();}};});
long legacyTelemetryStarted=System.nanoTime();
for(int target:new int[]{2,4})try{
 legacyTelemetryWorker.once(()->{if(System.nanoTime()-legacyTelemetryStarted>5_000_000_000L)throw new AssertionError("Legacy telemetry cycle stalled");return legacyTelemetryWorker.completedJobs()>=target&&legacyTelemetryWorker.pendingResults()==0;});
 throw new AssertionError("Legacy cycle ignored stop");
}catch(java.util.concurrent.CancellationException expected){}
check(reporterCreated.get()==1&&reporterStarted.get()==1&&reporterClosed.get()==0&&legacyTelemetry.count("complete")>=4);
legacyTelemetryWorker.stopPresence();check(reporterClosed.get()==1);
System.out.println("PASS: negotiated long blocks, grouped acknowledgements and stop recovery; repeated work, idle reset, settings retry, durable replay, disable, mandatory update, batch partial failure and restart, compute/upload overlap, blocked-upload cancellation and retained receipts, duplicate batch rejection, legacy fallback");}}
'''
}
with tempfile.TemporaryDirectory(prefix='enigma-network-cycle-') as folder:
 d=pathlib.Path(folder);files=[]
 for name,source in sources.items():
  f=d/name;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(source,encoding='utf-8');files.append(str(f))
 files += [str(f) for f in (root/'core/src/main/java').rglob('*.java') if f.name!='WorkEnvelope.java']
 files.append(str(root/'app/src/main/java/org/enigmagrid/android/NetworkWorker.java'))
 files.append(str(root/'app/src/main/java/org/enigmagrid/android/CpuOnlyProductionProfile.java'))
 files.append(str(root/'app/src/main/java/org/enigmagrid/android/CompletionTransport.java'))
 files.append(str(root/'core/CompletionTransportChecks.java'))
 files.append(str(root/'core/ServerTimeAnchorChecks.java'))
 files.append(str(root/'app/src/main/java/org/enigmagrid/android/GpuRpcGate.java'))
 files.append(str(root/'core/GpuRpcGateChecks.java'))
 files.append(str(root/'core/CpuOnlyProductionProfileChecks.java'))
 files.append(str(root/'core/WorkBlockQueueChecks.java'))
 files.append(str(root/'core/CpuOnlyPipelineTransitionChecks.java'))
 subprocess.run([str(jdk/'javac.exe'),'-encoding','UTF-8','-d',str(d),*files],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.android.NetworkCycleChecks'],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.android.CompletionTransportChecks'],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.core.ServerTimeAnchorChecks'],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.android.GpuRpcGateChecks'],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'org.enigmagrid.android.CpuOnlyProductionProfileChecks'],check=True)
 subprocess.run([str(jdk/'java.exe'),'-cp',str(d),'CpuOnlyPipelineTransitionChecks'],check=True)
